### ISSUE TITLE
OnChange attribute being removed

### ISSUE THREAD

**Issue by willodell** [revsystems/jQuery-SelectBox#20] opened 2011-03-03 15:15 UTC
We have used your code on various dropdowns on our ASP.NET based website without any issues.

Unfortunately on one particular dropdown box it is removing the "onchange" attribute, therefore preventing ASP.NET from raising a postback.

As soon as we stop applying the selectbox code to the dropdown box the onchange attribute appears and it works fine.

**Comment by designosis** [comment] 2011-03-14 07:21
Just adding my vote for prioritizing this issue.
For aesthetics, SelectBox is a usability designers wet dream.
But the lack of <b>&lt;select onchange="blah"&gt;</b> support cripples its functionality and user experience. Making a selection should immediately: (a) change focus to the next field, or (b) change the values of the next select list, or (c) all the other juicy stuff javascript was invented for.

**Comment by revsystems** [comment] 2011-03-15 21:04
I am unclear as to whether this is a jQuery issue or jQuery-SelectBox issue. It may be that the onchange attribute is not actually triggered by jQuery's "change" trigger. Functionality definitely exists to trigger the change function, but I've only tested with jQuery's own bindings.

If you bind the function with $("select").change(function() { alert("I changed"); }), does the issue still arise?

If so, at the very least, I can give you a work-around. I will also consider a separate plugin that forces jQuery rebinding for onchange attributes.

**Comment by MaxPower15** [comment] 2011-03-16 00:36
Actually, I'm having trouble reproducing your issue. I modified the second `<select>` on the [demo page](http://dl.dropbox.com/u/124192/websites/selectbox/index.html) (the one that starts with "Long dropdown test") to have an onchange attribute, and it seems to be working for me in Chrome, Firefox, IE9, all IE9's testing modes. Note that it only triggers the change when the value actually changes. You can change from one option to another, but if they have the same value, it won't trigger a change event.

Can you tell me what browser/jquery version you're experiencing this in? Also, if you have an example site or you could post a snippet on https://gist.github.com/, that might be helpful.

Thanks

**Comment by designosis** [comment] 2011-03-16 03:57
I'm so grateful for the replies. What I've just discovered - by using <b>&lt;select onchange="alert('yep')"&gt;</b> - is that onchange works. What doesn't work is <b>&lt;select onchange="$('#textarea').focus()"&gt;</b>, which DOES work when SelectBox is disabled. I hope this is insightful! Any ideas?

**Comment by designosis** [comment] 2011-03-16 04:15
I've just created a simple demonstration of the problem using the demo code (pared down ): http://designosis.com/sb/<br />
Something about binding focus, I take it :) Any workarounds?

**Comment by revsystems** [comment] 2011-03-16 13:28
Ah, that example really helps. I see the issue now. Yeah, by default, the select display is re-focused after you select an option. The problem is that the change() trigger occurs before this. So your change function is probably working correctly, but the focus is being moved back to the `select` anyway.

I will try to get a quick fix up for this. Good catch.

**Comment by revsystems** [comment] 2011-03-16 13:40
Okay, I just pushed a simple fix for this and set up an onchange example with focus() on the demo page (same `select` as before). Let me know if that fixes it for you.

**Comment by designosis** [comment] 2011-03-17 03:56
Flawless and excellent. It's amazing how satisfying it is when pieces click into place. Thank you for that!

**Comment by revsystems** [comment] 2011-03-17 04:09
Great, thanks!

**Closed as completed by revsystems** 2011-03-17 04:09 UTC
